version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply var-file="../environment/input_vars.tfvars" --auto-approve 