version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
      - terraform workspace select Dev || terraform workspace new Dev
  
  build:
    commands:
      - terraform destory var-file="../environment/input_vars.tfvars" --auto-approve 