version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USER --password-stdin
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan var-file="../environment/input_vars.tfvars" --auto-approve 